### ISSUE TITLE
External dataset re-downloaded when a different scene from a previously downloaded dataset is used. 

### ISSUE THREAD

**Issue by deivse** [nerfbaselines/nerfbaselines#34]
# Steps to reproduce:
1. Invoke `nerfbaselines` with scene A from dataset X, eg. `external://mipnerf360/garden`
1. Invoke `nerfbaselines` with scene B from dataset X, eg. `external://mipnerf360/kitchen`

# Expected behavior
Dataset is downloaded on first invocation, cached download is used on second invocation

# Actual behavior
Dataset is downloaded for each scene separately.

**Comment by jkulhanek** [comment]
Hi, by default, when you use `--data external://` only the specified scene is downloaded and cached locally. Unfortunately, for mipnerf360 this means a zip file with multiple scenes is downloaded and only the specific scene is extracted (to save space on disk). If you want to download all scenes from a dataset use the following command: `nerfbaselines download-dataset external://mipnerf360`. See here: https://nerfbaselines.github.io/docs/cli.html#nerfbaselines-download-dataset This will download can cache all scenes so that consecutive commands do not need to download anything.

**Comment by deivse** [comment]
Thanks for the reply, I understand. In my opinion it would be best if the download would be cached even when downloading the individual scene. But I fully understand that that's likely not a priority.

**Comment by jkulhanek** [comment]
That is the case currently, the downloaded scene is cached
